uploads = []
generated = []

[[outputs]]
id = "_B7urb-NS7N00TKkEwoZd"
uri = "file://README.md"
type = "text"
title = "WOLFBOT README.md (SEO Optimized)"

[[outputs]]
id = "PhsGcEe4-QZPNT6wPlADh"
uri = "file://tostatus.txt"
type = "text"
title = "tostatus — Full Code & Documentation"

[[outputs]]
id = "aeNoAN-97L1lLoVfcVsoO"
uri = "file://egg-nodejs-wolfbot.json"
type = "unspecified"
title = "Node.js Generic Bot Egg (Auto npm install on startup)"
